### ISSUE TITLE
question about detection

### ISSUE THREAD

**Issue by kandreta** [YangerOne6/Rust-recoil-script-with-auto-detect#4]
I have never touched anything related to cheat development but is there anything you have to do this for it to bypass EAC? (will i get banned)

**Comment by YangerOne6** [comment]
its fully external and doesent interact with your game, only your mouse.

**Comment by kandreta** [comment]
why would people sell scripts then if anyone can get them free and be undetected

**Comment by YangerOne6** [comment]
idk. i only added auto detect to an already public script.

**Comment by kandreta** [comment]
you haven't tested it?

**Comment by YangerOne6** [comment]
when did i say that?

**Comment by kandreta** [comment]
nevermind i just got it from you saying "i only added auto detect to an already public script.", i think the best thing to do to make it undetectable is add randomization and offsets.

**Comment by YangerOne6** [comment]
if you higher the sens it wont control the recoil as much, then you can just control the rest and it will be a lot easier and partiually human.
